### ISSUE TITLE
Decoder should keep state of reconnection time and last event ID

### ISSUE THREAD

**Issue by dolmen** [alevinval/sse#30]
I carefully read the spec and I'm convinced that the Decoder should track the state of reconnection time and last event ID.

I'm working on a post #29 patch that will change the Decoder constructor to have initial values and keep track of changes. The Event object will loose `retry` and will expose LastEventId instead of ID. LastEventId will be a copy of the internal state (instead of being either empty or non-empty depending on a kind of block that the current code implements but that is is not in the spec).

**Comment by dolmen** [comment]
@alevinval By the way, could you give me a push permission that would allow me to push branches directly in your repo (but not push on master)? That would ease collaboration.

**Comment by alevinval** [comment]
Hi @dolmen, you sound right. 

Doing this at decoder level makes sense, it will ease the pain. 
I am curious, do you intend to use a channel for eventsource to get notified on retry value changes or will retry be read/set everytime?

I just sent you the invite.

**Comment by alevinval** [comment]
I just realised that there is no need to notify eventsource of changes in retry value, since retry value is only used when connection drops.

I made a PR since I could not resist making the improvements.

I still need to work on accepting different initialisation values for the Decoder, for LastEventID. Maybe opening a different issue for that its better idea.
