### ISSUE TITLE
decoder: pure CR not recognized as end of line

### ISSUE THREAD

**Issue by dolmen** [alevinval/sse#4]
The [EventSource specification](https://html.spec.whatwg.org/multipage/comms.html#parsing-an-event-stream) also allows pure CR (without LF) as end-of-line but the current implementation doesn't recognize this.

**Comment by alevinval** [comment]
Thanks for reporting the issue. I was aware, and too lazy to fix it.

You motivated me to tackle it, see commit 7514843b516c1c0f88ce166694ea9ff005098266.
I kept your optimisations, the ones that were still needed.

There was another bug, since I was using `bufio.ReadSlice` instead of `bufio.ReadBytes`, when reading lines, if the buffer was full, the error wasn't handled and the reader was not fully read. This affected the benchmarks only.

I will close that bug.

**Comment by dolmen** [comment]
My refactoring is in decoder, using `bufio.Scanner`. Benchmarks looks good so far, but I still have a failing test case. I will probably push it this evening.

**Comment by alevinval** [comment]
I will avoid touching decoder then.
